### PR TITLE
Fix sudo issue #10

### PR DESCRIPTION
**Pull request by ankitjain28may**

### CODE REVIEW

**Comment by danenania** [comment]
Thanks! This is tricky because I believe there will also be errors *without* using `sudo` in other contexts (like on stock ubuntu). I think I'd prefer a `--disable-linux-sudo` flag or something along those lines to just outright removing it.

**Comment by ankitjain28may** [comment]
We can use `sudo` while running this file so we don't need sudo to write directly in a file.

**Comment by danenania** [comment]
Yeah, I see your point. I'm going to think about this a bit more to make sure existing users depending on this behavior wouldn't have problems, but leaving `sudo` up to the user would probably be cleaner. A permissions check on `/usr/local/bin` along with a good error message when `sudo` is required could be a good compromise.

**Comment by danenania** [comment]
Thinking about this some more, a better approach might be to simply check whether `sudo` is available

**Comment by ankitjain28may** [comment]
I don't think existing people would face any problem with this as it is one time while installing the envkey-fetch and it should be standard that we must have to follow.

**Comment by danenania** [comment]
A lot of folks have that install line scripted/automated, so a change could cause problems. What I'm now thinking we could do is just check whether `sudo` is needed/available and leave it out if not.

**Pull request closed without merging**
